# .github/workflows/deploy.yml
name: 部署 Angular 練習專案

on:
  push:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: 檢出代碼
        uses: actions/checkout@v4

      - name: 設置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: 安裝依賴
        run: npm ci

      - name: 建置 Angular 應用
        run: npm run build -- --configuration production --base-href /Angular-practise/

      - name: 檢查建置結果並創建 404.html
        run: |
          echo "=== 檢查 dist 目錄結構 ==="
          find dist/ -type f -name "*.html" | head -10

          echo "=== 查找 index.html 位置 ==="
          INDEX_FILE=$(find dist/ -name "index.html" -type f | head -1)
          echo "找到 index.html: $INDEX_FILE"

          if [ -f "$INDEX_FILE" ]; then
            DIST_DIR=$(dirname "$INDEX_FILE")
            cp "$INDEX_FILE" "$DIST_DIR/404.html"
            echo "404.html 已創建在: $DIST_DIR/404.html"
            
            # 設置環境變數供後續步驟使用
            echo "DIST_PATH=$DIST_DIR" >> $GITHUB_ENV
          else
            echo "錯誤: 找不到 index.html"
            exit 1
          fi

      - name: 設置 GitHub Pages
        uses: actions/configure-pages@v4

      - name: 上傳 GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DIST_PATH }}

      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
